server {
    listen 80;
    server_name api.nexosocial.id.vn auth.nexosocial.id.vn;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 200 'OK';
        add_header Content-Type text/plain;
    }
}
